PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS tenants (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,tenant_type TEXT NOT NULL CHECK (tenant_type IN ('OSC','COURSE','CONSULTANCY')),status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,core_enabled INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,full_name TEXT NOT NULL,password_hash TEXT NOT NULL,password_salt TEXT NOT NULL,platform_role TEXT NOT NULL DEFAULT 'USER',status TEXT NOT NULL DEFAULT 'ACTIVE',last_login_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memberships (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL CHECK (role IN ('OSC_ADMIN','TENANT_ADMIN','INSTRUCTOR','STUDENT')),status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(tenant_id,user_id),FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS courses (id TEXT PRIMARY KEY,product_id TEXT NOT NULL,name TEXT NOT NULL,live_duration_minutes INTEGER NOT NULL DEFAULT 120,practice_days INTEGER NOT NULL DEFAULT 30,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(product_id) REFERENCES products(id));
CREATE TABLE IF NOT EXISTS cohorts (id TEXT PRIMARY KEY,course_id TEXT NOT NULL,tenant_id TEXT NOT NULL,name TEXT NOT NULL,live_at TEXT,starts_at TEXT NOT NULL,expires_at TEXT NOT NULL,forum_status TEXT NOT NULL DEFAULT 'OPEN',status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(course_id) REFERENCES courses(id),FOREIGN KEY(tenant_id) REFERENCES tenants(id));
CREATE TABLE IF NOT EXISTS cohort_enrollments (id TEXT PRIMARY KEY,cohort_id TEXT NOT NULL,user_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(cohort_id,user_id),FOREIGN KEY(cohort_id) REFERENCES cohorts(id),FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS licenses (id TEXT PRIMARY KEY,tenant_id TEXT NOT NULL,product_id TEXT NOT NULL,cohort_id TEXT,license_type TEXT NOT NULL CHECK (license_type IN ('COURSE_30_DAYS','CONSULTANCY')),starts_at TEXT NOT NULL,expires_at TEXT,seat_limit INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(tenant_id) REFERENCES tenants(id),FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(cohort_id) REFERENCES cohorts(id));
CREATE TABLE IF NOT EXISTS workspaces_v4 (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,product_id TEXT NOT NULL,tenant_id TEXT,status TEXT NOT NULL DEFAULT 'ACTIVE',retention_until TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(user_id,product_id),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(product_id) REFERENCES products(id),FOREIGN KEY(tenant_id) REFERENCES tenants(id));
CREATE TABLE IF NOT EXISTS forum_topics (id TEXT PRIMARY KEY,cohort_id TEXT NOT NULL,author_user_id TEXT NOT NULL,module_key TEXT NOT NULL DEFAULT 'GENERAL',title TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'OPEN',pinned INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(cohort_id) REFERENCES cohorts(id),FOREIGN KEY(author_user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS forum_replies (id TEXT PRIMARY KEY,topic_id TEXT NOT NULL,author_user_id TEXT NOT NULL,body TEXT NOT NULL,instructor_answer INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(topic_id) REFERENCES forum_topics(id),FOREIGN KEY(author_user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT UNIQUE NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS password_reset_tokens (id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token_hash TEXT UNIQUE NOT NULL,expires_at TEXT NOT NULL,used_at TEXT,created_at TEXT NOT NULL,FOREIGN KEY(user_id) REFERENCES users(id));
CREATE TABLE IF NOT EXISTS audit_log (id TEXT PRIMARY KEY,actor_user_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,detail_json TEXT,created_at TEXT NOT NULL,FOREIGN KEY(actor_user_id) REFERENCES users(id));
CREATE INDEX IF NOT EXISTS idx_memberships_user ON memberships(user_id,status);
CREATE INDEX IF NOT EXISTS idx_enrollments_user ON cohort_enrollments(user_id,status);
CREATE INDEX IF NOT EXISTS idx_cohorts_expiry ON cohorts(expires_at,status);
CREATE INDEX IF NOT EXISTS idx_licenses_tenant ON licenses(tenant_id,status,expires_at);
CREATE INDEX IF NOT EXISTS idx_topics_cohort ON forum_topics(cohort_id,created_at);
CREATE INDEX IF NOT EXISTS idx_replies_topic ON forum_replies(topic_id,created_at);
CREATE INDEX IF NOT EXISTS idx_sessions_hash ON sessions(token_hash,expires_at);

